version: 2

jobs:
  build:
    test:
      docker:
        - image: circleci/ruby:2.5.3
      working_directory: ~/repo
      steps:
        - checkout
        - run:
            name: Run test
            command: ruby test.rb
